### ISSUE TITLE
Whether amd 5800h is supported

### ISSUE THREAD

**Issue by akwangl** [NootInc/WhateverRed#21] opened 2023-03-08 06:23 UTC
**I saw the following code in the submission, may I ask whether we can support AMD 5600H kernel display driver in the future**
![image](https://user-images.githubusercontent.com/39325175/223634805-11866308-e0bb-409d-b110-904baf4e46f9.png)

AMD 5600H CPU-Z
![image](https://user-images.githubusercontent.com/39325175/223634842-5efd40b9-5f16-4b3d-a396-4ff44bf6450e.png)
![image](https://user-images.githubusercontent.com/39325175/223634883-1d88c70d-a949-477d-bb30-bc2ee43ff3f0.png)

**Comment by ChefKissInc** [comment] 2023-03-08 06:24
Duplicate of #11

**Closed** 2023-03-08 06:24 UTC
